"""Compile a saaristo corpus into systematic-literature-review (SLR) artifacts.

This module turns the corpus + screening decisions + study protocol into the
*reporting* layer of an SLR: a PRISMA 2020 flow diagram, a Markdown manuscript
scaffold, and a Marp slide deck. `export.py` wraps these with file-writing
entry points; the CLI / MCP / HTTP surfaces call those.

Design principle — **never fabricate**. Everything mechanical and true is
auto-filled and traces to a source:

- counts come from `study.funnel()` (the DB),
- references from the `included` papers,
- theme headings from OpenAlex's *own* per-paper topic classification
  (factual metadata kept in `.saaristo/raw/openalex/<id>.json`),
- every exclusion reason from a recorded `screening_note`.

Interpretive prose (background, per-theme synthesis, discussion) is emitted as
visible ``<!-- WRITE: ... -->`` slots — a human or an LLM authors it, saari
never invents it. An honest Limitations block is auto-written so the draft
cannot overclaim (single source, single reviewer, abstract-only screening, no
registration).

The pure builder/render functions take injected data so they are unit-testable
without a database; the ``*_data`` / ``landscape_points`` wrappers do the DB I/O.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from saari import db, paths, projection, study
from saari.export import _citation_key
from saari.models import Paper

BANNER = (
    "<!--\n"
    "  Generated by saari (`saari export`). Mechanical content below — counts,\n"
    "  tables, references, figures — is auto-filled and traces to the corpus DB.\n"
    "  Lines marked `<!-- WRITE: ... -->` are synthesis slots: a human or an LLM\n"
    "  must author them. saari does not invent findings. Verify every claim\n"
    "  against the cited sources before submission.\n"
    "-->\n"
)


def _slot(label: str) -> str:
    """A visible authoring slot: an HTML comment plus an italic placeholder."""
    return f"<!-- WRITE: {label} -->\n\n_[{label} — to be written.]_\n"


# --------------------------------------------------------------------------- #
# PRISMA flow
# --------------------------------------------------------------------------- #

def build_prisma(funnel: dict[str, Any], excluded: list[Paper]) -> dict[str, Any]:
    """Assemble a PRISMA 2020 flow structure from a funnel dict + excluded papers.

    Pure: give it `study.funnel()` output and the list of `excluded` papers and
    it returns the flow numbers, splitting identification by search `source`
    (database searches vs snowballing) and bucketing exclusions by their
    recorded `screening_note`.
    """
    searches = funnel.get("searches", [])
    by_source: dict[str, int] = {}
    for s in searches:
        src = (s.get("source") or "unknown").strip() or "unknown"
        by_source[src] = by_source.get(src, 0) + int(s.get("n_returned") or 0)
    n_snowball = by_source.get("snowball", 0)
    n_database = sum(v for k, v in by_source.items() if k != "snowball")

    n_fetched = int(funnel.get("n_fetched", 0))
    n_unique = int(funnel.get("n_unique", 0))
    # Papers can enter the corpus outside any recorded search event (added
    # directly by id, seeded, etc.). Attribute those to an "other" bucket so
    # the funnel stays arithmetically consistent: identified >= unique, and
    # duplicates removed is exact instead of clamped.
    n_other = max(n_unique - n_fetched, 0)
    n_total = n_fetched + n_other
    n_duplicates_removed = n_total - n_unique

    by_status = funnel.get("by_status", {})
    n_included = int(by_status.get("included", 0))
    n_excluded = int(by_status.get("excluded", 0))
    n_maybe = int(by_status.get("maybe", 0))
    n_candidate = int(by_status.get("candidate", 0))
    n_screened = n_included + n_excluded + n_maybe

    reasons: dict[str, int] = {}
    for p in excluded:
        note = (p.screening_note or "").strip() or "no reason recorded"
        reasons[note] = reasons.get(note, 0) + 1

    return {
        "identification": {
            "by_source": by_source,
            "n_database": n_database,
            "n_snowball": n_snowball,
            "n_other": n_other,
            "n_total": n_total,
        },
        "n_duplicates_removed": n_duplicates_removed,
        "n_unique": n_unique,
        "n_screened": n_screened,
        "n_unscreened": n_candidate,
        "n_maybe": n_maybe,
        "excluded": {"n": n_excluded, "reasons": dict(sorted(reasons.items(), key=lambda kv: -kv[1]))},
        "n_included": n_included,
    }


def prisma_data(project_root: Path | None = None) -> dict[str, Any]:
    """DB wrapper: `study.funnel()` + excluded papers -> `build_prisma()`."""
    root = project_root or paths.project_root()
    funnel = study.funnel(root)
    with db.connect(paths.db_path(root)) as con:
        excluded = db.list_papers(
            con, limit=1_000_000, status="excluded", order_by="first_seen_at ASC"
        )
    return build_prisma(funnel, excluded)


def _reasons_lines(reasons: dict[str, int]) -> str:
    if not reasons:
        return "no exclusions recorded"
    return "; ".join(f"{note} (n={n})" for note, n in reasons.items())


def render_prisma_mermaid(data: dict[str, Any]) -> str:
    """PRISMA flow as a Mermaid `flowchart` (renders on GitHub / via Pandoc)."""
    idn = data["identification"]
    src_line = f"database searches: {idn['n_database']} · snowballing: {idn['n_snowball']}"
    if idn.get("n_other"):
        src_line += f" · other: {idn['n_other']}"
    ident = f"Records identified (n={idn['n_total']})<br/>{src_line}"
    dedup = f"Records after duplicates removed (n={data['n_unique']})<br/>duplicates removed: {data['n_duplicates_removed']}"
    screened = f"Records screened (n={data['n_screened']})"
    if data["n_unscreened"]:
        screened += f"<br/>awaiting screening: {data['n_unscreened']}"
    excluded = f"Records excluded (n={data['excluded']['n']})<br/>{_reasons_lines(data['excluded']['reasons'])}"
    included = f"Studies included in review (n={data['n_included']})"
    return (
        "flowchart TD\n"
        f'    A["{ident}"] --> B["{dedup}"]\n'
        f'    B --> C["{screened}"]\n'
        f'    C --> X["{excluded}"]\n'
        f'    C --> D["{included}"]\n'
    )


def _svg_box(x: int, y: int, w: int, h: int, lines: list[str]) -> str:
    parts = [
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6" '
        f'fill="#f5f7fa" stroke="#334155" stroke-width="1.5"/>'
    ]
    line_h = 18
    ty = y + 24
    for ln in lines:
        parts.append(
            f'<text x="{x + w // 2}" y="{ty}" text-anchor="middle" '
            f'font-family="sans-serif" font-size="13" fill="#0f172a">{html.escape(ln)}</text>'
        )
        ty += line_h
    return "\n".join(parts)


def _svg_arrow(x1: int, y1: int, x2: int, y2: int) -> str:
    return (
        f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#334155" '
        f'stroke-width="1.5" marker-end="url(#arrow)"/>'
    )


def render_prisma_svg(data: dict[str, Any]) -> str:
    """PRISMA flow as a self-contained, dependency-free SVG (fixed layout)."""
    idn = data["identification"]
    reasons = data["excluded"]["reasons"]
    reason_lines = [f"{note} (n={n})" for note, n in list(reasons.items())[:4]] or ["no reasons recorded"]
    # The side box is 250px wide with centered, non-wrapping text.
    reason_lines = [ln if len(ln) <= 36 else ln[:33] + "..." for ln in reason_lines]

    W, H = 840, 620
    bx, bw = 210, 300  # main column x, width
    boxes = [
        _svg_box(bx, 20, bw, 70, [
            f"Records identified (n={idn['n_total']})",
            f"database: {idn['n_database']}  ·  snowballing: {idn['n_snowball']}"
            + (f"  ·  other: {idn['n_other']}" if idn.get("n_other") else ""),
        ]),
        _svg_box(bx, 160, bw, 70, [
            f"Records after de-duplication (n={data['n_unique']})",
            f"duplicates removed: {data['n_duplicates_removed']}",
        ]),
        _svg_box(bx, 300, bw, 50, [
            f"Records screened (n={data['n_screened']})",
            *( [f"awaiting screening: {data['n_unscreened']}"] if data["n_unscreened"] else [] ),
        ]),
        _svg_box(bx, 470, bw, 50, [
            f"Studies included (n={data['n_included']})",
        ]),
        # side box: exclusions with reasons
        _svg_box(bx + bw + 40, 300, 250, 20 + 18 * (len(reason_lines) + 1), [
            f"Records excluded (n={data['excluded']['n']})",
            *reason_lines,
        ]),
    ]
    arrows = [
        _svg_arrow(bx + bw // 2, 90, bx + bw // 2, 160),
        _svg_arrow(bx + bw // 2, 230, bx + bw // 2, 300),
        _svg_arrow(bx + bw // 2, 350, bx + bw // 2, 470),
        _svg_arrow(bx + bw, 325, bx + bw + 40, 325),
    ]
    defs = (
        '<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" '
        'orient="auto" markerUnits="strokeWidth">'
        '<path d="M0,0 L8,3 L0,6 Z" fill="#334155"/></marker></defs>'
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" role="img" aria-label="PRISMA flow diagram">\n'
        f"{defs}\n" + "\n".join(boxes + arrows) + "\n</svg>\n"
    )


# --------------------------------------------------------------------------- #
# Thematic grouping (from OpenAlex topics — factual, not invented)
# --------------------------------------------------------------------------- #

def _primary_topic_label(topics: list[dict]) -> str | None:
    """Label of a paper's primary (top-ranked) OpenAlex topic.

    Prefers the specific topic name (e.g. 'Semantic Web and Ontologies') over the
    coarse `subfield`/`field` (which collapse a whole corpus into 'Artificial
    Intelligence' / 'Computer Science'), falling back up the hierarchy.
    """
    if not topics:
        return None
    top = topics[0]
    for key in ("display_name",):
        if top.get(key):
            return top[key]
    for level in ("subfield", "field", "domain"):
        v = (top.get(level) or {}).get("display_name")
        if v:
            return v
    return None


def group_by_topic(
    papers: list[Paper], topic_field: dict[str, str | None]
) -> dict[str, list[Paper]]:
    """Group papers by their primary-topic field. Pure: `topic_field` maps
    paper.id -> field name (or None). Missing -> 'Uncategorized'. Groups are
    ordered by size (largest theme first), 'Uncategorized' always last.
    """
    groups: dict[str, list[Paper]] = {}
    for p in papers:
        theme = topic_field.get(p.id) or "Uncategorized"
        groups.setdefault(theme, []).append(p)
    ordered = sorted(
        groups.items(),
        key=lambda kv: (kv[0] == "Uncategorized", -len(kv[1]), kv[0]),
    )
    return dict(ordered)


def theme_groups(
    project_root: Path | None = None, status: str | None = "included"
) -> dict[str, list[Paper]]:
    """DB+raw wrapper: group `status` papers by OpenAlex primary-topic field."""
    root = project_root or paths.project_root()
    with db.connect(paths.db_path(root)) as con:
        papers = db.list_papers(
            con, limit=1_000_000, status=status,
            order_by="cited_by_count DESC NULLS LAST",
        )
        topic_field: dict[str, str | None] = {}
        for p in papers:
            raw_rel = db.get_raw_path(con, p.id)
            topics: list[dict] = []
            if raw_rel:
                full = root / raw_rel
                if full.exists():
                    try:
                        topics = json.loads(full.read_text()).get("topics") or []
                    except (OSError, json.JSONDecodeError):
                        topics = []
            topic_field[p.id] = _primary_topic_label(topics)
    return group_by_topic(papers, topic_field)


# --------------------------------------------------------------------------- #
# Landscape figure (static SVG scatter)
# --------------------------------------------------------------------------- #

_STATUS_COLORS = {
    "included": "#16a34a",
    "excluded": "#cbd5e1",
    "maybe": "#f59e0b",
    "candidate": "#94a3b8",
}


def render_landscape_svg(points: list[dict[str, Any]], width: int = 720, height: int = 520) -> str:
    """Static SVG scatter of the 2D projection, colored by screening status.

    Pure: `points` = [{x, y, status, title, cited}]. Complements the existing
    interactive `landscape.html`; this one is print-ready for the manuscript.
    """
    if not points:
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">'
            f'<text x="20" y="30" font-family="sans-serif" font-size="14">No projection — run `saari refresh`.</text>'
            f"</svg>\n"
        )
    margin = 40
    xs = [p["x"] for p in points]
    ys = [p["y"] for p in points]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    span_x = max(max_x - min_x, 1e-9)
    span_y = max(max_y - min_y, 1e-9)
    aw, ah = width - 2 * margin, height - 2 * margin

    circles = []
    for p in points:
        cx = margin + (p["x"] - min_x) / span_x * aw
        cy = margin + (p["y"] - min_y) / span_y * ah
        cited = int(p.get("cited") or 0)
        r = 3 + min(9.0, (cited ** 0.5) / 6.0)
        color = _STATUS_COLORS.get(p.get("status", "candidate"), "#94a3b8")
        title = html.escape(str(p.get("title") or ""))[:120]
        circles.append(
            f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="{color}" '
            f'fill-opacity="0.75" stroke="#334155" stroke-width="0.4"><title>{title}</title></circle>'
        )
    # legend
    legend = []
    lx, ly = margin, height - 14
    for status, color in _STATUS_COLORS.items():
        legend.append(
            f'<circle cx="{lx}" cy="{ly}" r="5" fill="{color}"/>'
            f'<text x="{lx + 10}" y="{ly + 4}" font-family="sans-serif" font-size="11" fill="#334155">{status}</text>'
        )
        lx += 110
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-label="Corpus landscape">\n'
        f'<rect width="{width}" height="{height}" fill="#ffffff"/>\n'
        + "\n".join(circles) + "\n" + "\n".join(legend) + "\n</svg>\n"
    )


def landscape_points(
    project_root: Path | None = None, status: str | None = None
) -> list[dict[str, Any]]:
    """DB wrapper: join the 2D projection with paper metadata for the scatter."""
    root = project_root or paths.project_root()
    proj = {d["paper_id"]: (d["x"], d["y"]) for d in projection.get_projection(root)}
    with db.connect(paths.db_path(root)) as con:
        papers = db.list_papers(con, limit=1_000_000, status=status)
    pts: list[dict[str, Any]] = []
    for p in papers:
        if p.id in proj:
            x, y = proj[p.id]
            pts.append({
                "x": x, "y": y, "status": p.status,
                "title": p.title, "cited": p.cited_by_count or 0,
            })
    return pts


# --------------------------------------------------------------------------- #
# Markdown assembly helpers (pure)
# --------------------------------------------------------------------------- #

def _authors_short(p: Paper) -> str:
    names = [a.name for a in p.authors if getattr(a, "name", None)]
    if not names:
        return "—"
    first = names[0].split()[-1] if names[0].split() else names[0]
    return first if len(names) == 1 else f"{first} et al."


def characteristics_table(papers: list[Paper]) -> str:
    """Study-characteristics table — mechanical columns only (no interpretation)."""
    header = (
        "| Cite key | Authors | Year | Venue | Citations | OA | DOI |\n"
        "|---|---|---|---|---|---|---|\n"
    )
    rows = []
    for p in papers:
        doi = f"[{p.doi}](https://doi.org/{p.doi})" if p.doi else "—"
        rows.append(
            f"| `{_citation_key(p)}` | {_authors_short(p)} | {p.year or '—'} | "
            f"{(p.venue or '—')} | {p.cited_by_count if p.cited_by_count is not None else '—'} | "
            f"{p.oa_status or '—'} | {doi} |"
        )
    return header + "\n".join(rows) + "\n"


def search_strategy_table(searches: list[dict[str, Any]]) -> str:
    header = "| # | Source | Query | Date | Records |\n|---|---|---|---|---|\n"
    rows = []
    for i, s in enumerate(searches, 1):
        date = (s.get("created_at") or "")[:10]
        rows.append(
            f"| {i} | {s.get('source', '—')} | `{s.get('query', '')}` | {date} | {s.get('n_returned', '—')} |"
        )
    return header + "\n".join(rows) + "\n"


def reference_list(papers: list[Paper]) -> str:
    """Numbered reference list keyed by the same cite keys as the BibTeX export."""
    lines = []
    for i, p in enumerate(papers, 1):
        authors = ", ".join(a.name for a in p.authors if getattr(a, "name", None)) or "—"
        venue = f" *{p.venue}*." if p.venue else ""
        doi = f" https://doi.org/{p.doi}" if p.doi else ""
        lines.append(f"{i}. [`{_citation_key(p)}`] {authors} ({p.year or 'n.d.'}). {p.title}.{venue}{doi}")
    return "\n".join(lines) + "\n"


def limitations_block(by_source: dict[str, int] | None = None) -> str:
    """Auto-disclosed method limitations so the draft cannot overclaim.

    `by_source` (record counts per search source) makes the sources bullet
    factual: single-source wording only when a single database was used.
    """
    databases = sorted(k for k in (by_source or {}) if k not in ("snowball", "unknown"))
    if len(databases) > 1:
        src_bullet = (
            f"- **Bibliographic sources.** Records were identified via {len(databases)} "
            f"databases ({', '.join(databases)}) plus citation snowballing. Coverage is "
            "bounded by these databases' indexing and English-language metadata.\n"
        )
    else:
        db_name = databases[0] if databases else "OpenAlex"
        src_bullet = (
            f"- **Single bibliographic source.** Records were identified via the {db_name} API "
            "(plus citation snowballing), not multiple databases (e.g. Scopus, Web of Science, "
            f"IEEE Xplore). Coverage is bounded by {db_name} indexing and English-language metadata.\n"
        )
    return (
        "This review was produced with saari and carries the following method limitations, "
        "which readers should weigh:\n\n"
        + src_bullet
        + "- **Single-reviewer screening.** Inclusion/exclusion decisions were made by a single "
        "reviewer (human or LLM agent). There was no second independent reviewer and no "
        "inter-rater agreement statistic (e.g. Cohen's κ).\n"
        "- **Title/abstract screening only.** Unless full texts were separately retrieved and "
        "recorded, screening relied on titles and abstracts.\n"
        "- **No formal risk-of-bias / quality appraisal** was applied to included studies "
        "unless recorded separately.\n"
        "- **No prospective registration.** This protocol was not registered on PROSPERO or OSF.\n"
    )


# --------------------------------------------------------------------------- #
# Manuscript + slides assembly (pure — take injected data)
# --------------------------------------------------------------------------- #

def build_paper_md(
    study_rec: dict[str, Any],
    prisma: dict[str, Any],
    searches: list[dict[str, Any]],
    themes: dict[str, list[Paper]],
    included: list[Paper],
    prisma_fig: str = "prisma.svg",
    landscape_fig: str = "landscape.svg",
) -> str:
    title = (study_rec.get("title") or "").strip() or "A Systematic Literature Review"
    question = (study_rec.get("question") or "").strip()
    criteria = (study_rec.get("criteria") or "").strip()
    authors = (study_rec.get("authors") or "").strip()

    out: list[str] = [BANNER, f"# {title}\n"]
    if authors:
        out.append(f"*{authors}*\n")

    out.append("## Abstract\n")
    out.append(_slot("Structured abstract: background, objectives, methods, results, conclusions"))

    out.append("\n## 1. Introduction\n")
    out.append(_slot("Background and rationale — why this review is needed"))
    out.append("\n**Objective / research question.**\n")
    out.append(f"> {question}\n" if question else _slot("State the research question (set it with `saari study set --question`)"))

    out.append("\n## 2. Methods\n")
    out.append("\n### 2.1 Eligibility criteria\n")
    out.append(f"{criteria}\n" if criteria else _slot("Inclusion/exclusion criteria (set with `saari study set --criteria`)"))
    idn = prisma["identification"]
    out.append("\n### 2.2 Information sources and search strategy\n")
    other_clause = (
        f", plus {idn['n_other']} record(s) added outside recorded searches"
        if idn.get("n_other")
        else ""
    )
    out.append(
        f"Records were identified via database searches on the OpenAlex API "
        f"({idn['n_database']} records across {len([s for s in searches if (s.get('source') or '') != 'snowball'])} searches) "
        f"and citation snowballing ({idn['n_snowball']} records){other_clause}. "
        f"The full search log ({len(searches)} event(s)):\n\n"
    )
    out.append(search_strategy_table(searches))
    out.append("\n### 2.3 Selection process\n")
    out.append(
        f"Of {prisma['n_unique']} unique records, {prisma['n_screened']} were screened to a decision "
        f"({prisma['n_included']} included, {prisma['excluded']['n']} excluded, {prisma['n_maybe']} maybe); "
        f"{prisma['n_unscreened']} remain unscreened.\n"
    )
    out.append("\n### 2.4 Synthesis method\n")
    out.append(_slot("Describe the synthesis approach (narrative / thematic)"))
    out.append("\n### 2.5 Limitations of this review\n")
    out.append(limitations_block(prisma["identification"]["by_source"]))

    out.append("\n## 3. Results\n")
    out.append("\n### 3.1 Study selection\n")
    out.append(f"![PRISMA flow diagram]({prisma_fig})\n\n")
    out.append(_slot("Narrate the selection process (refer to the PRISMA diagram above)"))
    out.append("\n### 3.2 Corpus landscape\n")
    out.append(f"![Corpus landscape — 2D projection of the embedded corpus]({landscape_fig})\n\n")
    out.append("\n### 3.3 Study characteristics\n")
    out.append(characteristics_table(included))
    out.append("\n### 3.4 Synthesis of findings\n")
    if themes:
        for theme, papers in themes.items():
            keys = ", ".join(f"`{_citation_key(p)}`" for p in papers)
            out.append(f"\n#### {theme} (n={len(papers)})\n")
            out.append(f"Included papers: {keys}\n\n")
            out.append(_slot(f"Synthesize the '{theme}' theme"))
    else:
        out.append(_slot("Synthesize findings by theme"))

    out.append("\n## 4. Discussion\n")
    out.append(_slot("Summary of evidence, and how it answers the research question"))
    out.append("\n### 4.1 Research gaps\n")
    out.append(_slot("What the corpus does NOT cover — the white space / open problems"))

    out.append("\n## 5. Conclusion\n")
    out.append(_slot("Conclusions"))

    out.append("\n## References\n")
    out.append(reference_list(included))
    return "\n".join(out)


def build_slides_md(
    study_rec: dict[str, Any],
    prisma: dict[str, Any],
    themes: dict[str, list[Paper]],
    prisma_fig: str = "prisma.svg",
    landscape_fig: str = "landscape.svg",
) -> str:
    title = (study_rec.get("title") or "").strip() or "A Systematic Literature Review"
    question = (study_rec.get("question") or "").strip() or "[set with `saari study set --question`]"
    idn = prisma["identification"]

    slides: list[str] = [
        "---\nmarp: true\npaginate: true\ntheme: default\n---",
        f"<!-- Generated by saari. Slots marked [WRITE] need authoring. -->\n\n# {title}\n\n{study_rec.get('authors', '')}",
        f"## Research question\n\n> {question}",
        (
            "## Method\n\n"
            f"- Source: OpenAlex ({idn['n_database']} records) + snowballing ({idn['n_snowball']} records)\n"
            f"- {prisma['n_unique']} unique records after de-duplication\n"
            f"- {prisma['n_screened']} screened -> **{prisma['n_included']} included**\n\n"
            f"![w:520]({prisma_fig})"
        ),
        f"## Corpus landscape\n\n![w:760]({landscape_fig})",
    ]
    for theme, papers in (themes or {}).items():
        top = "\n".join(f"- `{_citation_key(p)}` ({p.year or 'n.d.'})" for p in papers[:5])
        slides.append(f"## Theme: {theme} (n={len(papers)})\n\n{top}\n\n<!-- WRITE: one-line takeaway for {theme} -->")
    slides.append("## Research gaps\n\n<!-- WRITE: the white space / open problems -->")
    slides.append("## Conclusion\n\n<!-- WRITE: conclusions -->")
    return "\n\n---\n\n".join(slides) + "\n"
